language: python
python:
  - "2.6"
  - "2.7"
  - "3.5"
  - "pypy"
# command to install dependencies
install:
  - echo `pwd`
  - ls
  - pip install -r requirements.txt
  - python setup.py develop
# command to run tests
script: py.test